package cotizacion.model;
// Generated 28/06/2018 09:50:21 PM by Hibernate Tools 4.3.1



/**
 * Socios generated by hbm2java
 */
public class Socios  implements java.io.Serializable {


     private Integer idSocio;
     private String nombreSocio;
     private Double tasa;
     private Double montoDisponible;

    public Socios() {
    }

    public Socios(String nombreSocio, Double tasa, Double montoDisponible) {
       this.nombreSocio = nombreSocio;
       this.tasa = tasa;
       this.montoDisponible = montoDisponible;
    }
   
    public Integer getIdSocio() {
        return this.idSocio;
    }
    
    public void setIdSocio(Integer idSocio) {
        this.idSocio = idSocio;
    }
    public String getNombreSocio() {
        return this.nombreSocio;
    }
    
    public void setNombreSocio(String nombreSocio) {
        this.nombreSocio = nombreSocio;
    }
    public Double getTasa() {
        return this.tasa;
    }
    
    public void setTasa(Double tasa) {
        this.tasa = tasa;
    }
    public Double getMontoDisponible() {
        return this.montoDisponible;
    }
    
    public void setMontoDisponible(Double montoDisponible) {
        this.montoDisponible = montoDisponible;
    }




}


